wellknown
=======

```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
```

`wellknown` - convert WKT and WKB to GeoJSON and vice versa.

## Install

```{r eval=FALSE}
install.packages("devtools")
devtools::install_github("sckott/wellknown")
```

```{r}
library("wellknown")
```

## GeoJSON to WKT

### Point

```{r}
point <- list('type' = 'Point', 'coordinates' = c(116.4, 45.2, 11.1))
geojson2wkt(point)
```

### LineString

```{r}
st <- list(type = 'LineString',
            coordinates = list(c(0.0, 0.0, 10.0), c(2.0, 1.0, 20.0),
                              c(4.0, 2.0, 30.0), c(5.0, 4.0, 40.0)))
geojson2wkt(st, fmt=0)
```

### Polygon

```{r}
poly <- list(type = 'Polygon',
      coordinates=list(
        list(c(100.001, 0.001), c(101.12345, 0.001), c(101.001, 1.001), c(100.001, 0.001)),
        list(c(100.201, 0.201), c(100.801, 0.201), c(100.801, 0.801), c(100.201, 0.201))
))
geojson2wkt(poly)
```


## WKT to GeoJSON

### Point

As a `Feature`

```{r}
str <- "POINT (-116.4000000000000057 45.2000000000000028)"
wkt2geojson(str)
```

Not a `Feature`

```{r}
wkt2geojson(str, feature=FALSE)
```

### Polygon

As a `Feature`

```{r}
str <- "POLYGON ((100 0.1, 101.1 0.3, 101 0.5, 100 0.1), (103.2 0.2, 104.8 0.2, 100.8 0.8, 103.2 0.2))"
wkt2geojson(str)
```

Not a `Feature`

```{r}
wkt2geojson(str, feature=FALSE)
```
