// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wk_dump_point
std::string wk_dump_point(List obj, int fmt, std::string third);
RcppExport SEXP _wellknown_wk_dump_point(SEXP objSEXP, SEXP fmtSEXP, SEXP thirdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< std::string >::type third(thirdSEXP);
    rcpp_result_gen = Rcpp::wrap(wk_dump_point(obj, fmt, third));
    return rcpp_result_gen;
END_RCPP
}
// wk_dump_multipoint
std::string wk_dump_multipoint(List obj, int fmt, std::string third);
RcppExport SEXP _wellknown_wk_dump_multipoint(SEXP objSEXP, SEXP fmtSEXP, SEXP thirdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< std::string >::type third(thirdSEXP);
    rcpp_result_gen = Rcpp::wrap(wk_dump_multipoint(obj, fmt, third));
    return rcpp_result_gen;
END_RCPP
}
// wk_dump_linestring
std::string wk_dump_linestring(List obj, int fmt, std::string third);
RcppExport SEXP _wellknown_wk_dump_linestring(SEXP objSEXP, SEXP fmtSEXP, SEXP thirdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< std::string >::type third(thirdSEXP);
    rcpp_result_gen = Rcpp::wrap(wk_dump_linestring(obj, fmt, third));
    return rcpp_result_gen;
END_RCPP
}
// wk_dump_multilinestring
std::string wk_dump_multilinestring(List obj, int fmt, std::string third);
RcppExport SEXP _wellknown_wk_dump_multilinestring(SEXP objSEXP, SEXP fmtSEXP, SEXP thirdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< std::string >::type third(thirdSEXP);
    rcpp_result_gen = Rcpp::wrap(wk_dump_multilinestring(obj, fmt, third));
    return rcpp_result_gen;
END_RCPP
}
// wk_dump_polygon
std::string wk_dump_polygon(List obj, int fmt, std::string third);
RcppExport SEXP _wellknown_wk_dump_polygon(SEXP objSEXP, SEXP fmtSEXP, SEXP thirdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< std::string >::type third(thirdSEXP);
    rcpp_result_gen = Rcpp::wrap(wk_dump_polygon(obj, fmt, third));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wellknown_wk_dump_point", (DL_FUNC) &_wellknown_wk_dump_point, 3},
    {"_wellknown_wk_dump_multipoint", (DL_FUNC) &_wellknown_wk_dump_multipoint, 3},
    {"_wellknown_wk_dump_linestring", (DL_FUNC) &_wellknown_wk_dump_linestring, 3},
    {"_wellknown_wk_dump_multilinestring", (DL_FUNC) &_wellknown_wk_dump_multilinestring, 3},
    {"_wellknown_wk_dump_polygon", (DL_FUNC) &_wellknown_wk_dump_polygon, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_wellknown(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
