# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wk_dump_point <- function(obj, fmt, third) {
    .Call('_wellknown_wk_dump_point', PACKAGE = 'wellknown', obj, fmt, third)
}

wk_dump_multipoint <- function(obj, fmt, third) {
    .Call('_wellknown_wk_dump_multipoint', PACKAGE = 'wellknown', obj, fmt, third)
}

wk_dump_linestring <- function(obj, fmt, third) {
    .Call('_wellknown_wk_dump_linestring', PACKAGE = 'wellknown', obj, fmt, third)
}

wk_dump_multilinestring <- function(obj, fmt, third) {
    .Call('_wellknown_wk_dump_multilinestring', PACKAGE = 'wellknown', obj, fmt, third)
}

wk_dump_polygon <- function(obj, fmt, third) {
    .Call('_wellknown_wk_dump_polygon', PACKAGE = 'wellknown', obj, fmt, third)
}

